FROM node:20.10.0
WORKDIR /app

ARG VITE_BASE_URL
ENV VITE_BASE_URL=$VITE_BASE_URL

ARG VITE_USERNAME
ENV VITE_USERNAME=$VITE_USERNAME

ARG VITE_PASSWORD
ENV VITE_PASSWORD=$VITE_PASSWORD

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build
CMD cp -r dist result_build
